### ISSUE TITLE
Search does not work as described

### ISSUE THREAD

**Issue by danielatdattrixdotcom** [cyrbil/python_keepass_http#1]
I can match on exact URL, but partial does not match nor does matching on name (title). Keepass 2.41 and most recent KeepassHTTP. I looked though KeepassHTTP source and it does not seem anything but full URL matching is possible.

**Comment by cyrbil** [comment]
Will look into this, but it's probably an issue on pfn/keepasshttp side, as the matching is quite a mess...
https://github.com/pfn/keepasshttp/blob/master/KeePassHttp/Handlers.cs#L117

In the meantime can you provide an example of a url and title missmatch ?

**Comment by danielatdattrixdotcom** [comment]
For me it will match on an exact URL or exact Title match, but not the partial part. I looked over the code here, and tests and saw it was not an issue here directly. But I saw the claim of partial search and was very hopeful to integrate with the Plasma desktop and not have to open the app to search. Thanks, I'll keep an eye out here.

**Comment by cyrbil** [comment]
Ok, tested it, and i'm still puzzled on how KeePassHTTP does the matching ...

```
"""
    For an entry like:

    title: "Example"
    url: "https://my.example.com/test"
"""
import keepasshttp
kph = keepasshttp.KeePassHTTP()


kph._request("get-logins", Url="Example") # Matches title exactly (case sensitive)
kph._request("get-logins", Url="*") # Finds most entries, no clues why some are left or why this works
kph._request("get-logins", Url="example.com") # fails
kph._request("get-logins", Url="my.example.com") # matches
kph._request("get-logins", Url="my.example.com/test") # matches
kph._request("get-logins", Url="my.example.com/te") # fails
kph._request("get-logins", Url="https://my.example.com/te") # matches
kph._request("get-logins", Url="https://my.example.com/wtf") # matches
kph._request("get-logins", Url="wtf://my.example.com/wtf") # matches
```
So basically:

  - Title matching is case sensitive and requires complete exact match
  - Url matching is not case sensitive
  - Url matching must have full domain
  - Url matching can have any path only when a protocol is specified
  - Url matching can have any protocols
